import Head from 'next/head'
import { Navbar } from '../components/Navbar/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mars High Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  )
}