import Head from 'next/head'
import { Navbar } from '../components/Navbar/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mars High Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
    </>
  )
}

// Pas besoin de NavBar directement dans la page je la mettrais dans un provider qui alimentera toute l'appli
// je te montrerais sur quelles pages tu peut le faire apparaitre.